spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: crypto-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/crypto_db
    username: crypto_user
    password: crypto_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

clickhouse:
  url: jdbc:clickhouse://localhost:8123/crypto_db
  username: default
  password: ""
