spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: crypto-group
      auto-offset-reset: earliest

  datasource:
    url: jdbc:mysql://localhost:3306/crypto_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: crypto_user
    password: crypto_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

