spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: crypto-group
      auto-offset-reset: earliest

  datasource:
    url: jdbc:mysql://mysql:3306/crypto_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: crypto_user
    password: crypto_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# HikariCP connection pool retry settings
spring.datasource.hikari.initialization-fail-timeout: 60000
spring.datasource.hikari.connection-timeout: 20000
spring.datasource.hikari.validation-timeout: 5000
spring.datasource.hikari.max-lifetime: 1800000
