spring:
  kafka:
    bootstrap-servers: localhost:9092    # Kafka broker address
    consumer:
      group-id: demo-consumer            # Identifies this consumer group
      auto-offset-reset: earliest        # If no offset is stored, read from beginning
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/kafka_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: linu
    password: linukafka
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create / update / validate / none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
